### ISSUE TITLE
Can't add a plugin in a new row

### ISSUE THREAD

**Issue by rboixaderg** [react-page/react-page#821] opened 2020-06-05 07:51 UTC
**Describe the bug**
It is impossible add a new plugin above or under when there are two columns or more.

**To Reproduce**
1. Add two plugins, in two columns
2. Try to add a new plugin above or under this two columns

**Expected behavior**
Add a plugin in a new row whenever you want

**Additional context**
I attach a zip file, because i can't upload a .mov file
[test_video.mov.zip](https://github.com/react-page/react-page/files/4734671/test_video.mov.zip)

**Comment by macrozone** [comment] 2020-06-05 08:45
@rboixaderg I also noticed this and i am not sure if this is a regression from the "allow resize in editmode" change,

@PeterKottas maybe you can help?

**Comment by macrozone** [comment] 2020-06-05 08:51
actually i don't think its a regression from that. I noticed that in this case, there is no row around the cells, need to investigate

**Comment by PeterKottas** [comment] 2020-06-05 12:05
Definitely not a regression. This "could" happen when you don't surround your initial state with an extra cell. I am not sure if this is a result of fiddling manually with the initial state JSON or if it somehow happened by mistake. TBH, I doubt it happened on its own cause I think I would have seen it in the 2 years I've been working with this. But you never know. 

Example of an empty state (notice the cells => one parent cell => rows => then the actual cell)
```
{
    id: '1',
    cells: [
      {
        id: undefined,
        inline: null,
        size: 12,
        rows: [
          {
            id: undefined,
            cells: [
              {
                id: undefined,
                inline: null,
                size: 12,
                content: {
                  plugin: {
                    name: 'ory/editor/core/content/slate',
                    version: '0.0.2',
                  },
                  state: {
                    value: [
                      {
                        type: 'PARAGRAPH',
                        children: [
                          {
                            text: '',
                          },
                        ],
                      },
                    ],
                    version: 1,
                  },
                },
              },
            ],
          },
        ],
      },
    ],
  }
```

**Comment by rboixaderg** [comment] 2020-06-06 06:10
Hi! I have been tried it more times, and not always it happen, but it is difficult to find a few steps to reproduce it always!  I don't modify initial state!

**Comment by PeterKottas** [comment] 2020-06-06 12:02
I see, so in that case, it's crucial to explain these steps in detail and/or with a video. Also, it would be useful if you could include your initial state and try to find the least possible amount of steps that lead to this "broken" state.

**Comment by macrozone** [comment] 2020-06-06 12:20
@PeterKottas he showed a video from the example app. That might help

@rboixaderg in this case, there is a default plugin already there which has has two columns, can you reproduce it also with slate as default plugin?

@PeterKottas i think one problem is, that the Editable has first cells and not rows. So if you have a state with two cells, each with a size of 6, you can't add a row below with size 12. You first have to move one of these cells below and have a size of 6. This will create rows in this first cell.

i think it would be better if we would start with row or we should add some sanitization that will alway guarante that there is one full size row

**Comment by rboixaderg** [comment] 2020-06-06 13:50
I can reproduce it with the `customLayoutPluginWithInitialState` as a default plugin. I use example folder that it is in source code. Usually it happens when I add a new plugin inside de customLayoutPluginWithInitialState and then delete all plugins that there are insiside de layout, and finally I add a second column. After that I can't add a new plugin. 

Video:
[Gravació de pantalla 2020-06-06 a les 15.34.27.mov.zip](https://github.com/react-page/react-page/files/4740116/Gravacio.de.pantalla.2020-06-06.a.les.15.34.27.mov.zip)

If the slate plugin is a default plugin, it happens always. 
Video
[Gravació de pantalla 2020-06-06 a les 15.48.36.mov.zip](https://github.com/react-page/react-page/files/4740120/Gravacio.de.pantalla.2020-06-06.a.les.15.48.36.mov.zip)

**Comment by PeterKottas** [comment] 2020-06-06 15:16
> he showed a video from the example app. That might help

I think the initial video only showed the state after it was broken. But never mind, the new videos are quite clear.

> I think one problem is, that the Editable has first cells and not rows. So if you have a state with two cells, each with a size of 6, you can't add a row below with size 12. You first have to move one of these cells below and have a size of 6. This will create rows in this first cell. I think it would be better if we would start with a row or we should add some sanitization that will always guarantee that there is one full-size row

That sounds like you got it. We should definitely have row as the uppermost component in the state. Not sure where how exactly to change it but it for sure makes perfect sense for it to behave that way. 

Btw I can verify this happens on our side. The thing is though, for our use case since we mostly show content on mobile, the columns are not all that widely adopted I guess. It never came up as an issue so far at least.

@rboixaderg thanks, especially the second video is exactly what we need. I personally cannot allocate time to fix this at the moment. If this is something that is important for you, it would be great if you dug in and contributed a PR ;-) I'd be happy to check that. Otherwise, maybe @macrozone can help. Maybe for you guys, columns are more widely use than for us in GuestBell.

**Comment by macrozone** [comment] 2020-11-06 13:16
@rboixaderg when https://github.com/react-page/react-page/issues/874 lands, can you check? that will be the next 1.0.0 beta version. It will switch from having cells as top-most nodes to having rows instead

**Comment by rboixaderg** [comment] 2020-11-07 08:48
Hi @macrozone I have check it in 1.0.0-beta-14 and it's works! 
Thanks!

**Comment by macrozone** [comment] 2021-01-12 17:48
fixed in beta

**Closed by macrozone** 2021-01-12 17:48 UTC
Labels: bug, wontfix
