### ISSUE TITLE
Parallax Image | onFocus State to toggle BottomToolbar != Working

### ISSUE THREAD

**Issue by KamesCG** [react-page/react-page#490] opened 2017-11-14 12:13 UTC
First, thank you for such an amazing tool - I'm absolutely loving it!

I noticed in the demo https://editor.ory.am/, the parallax image plugin works as expected.

However, in the Github examples, and also using the package in my application, the onFocus function seems like it's not being called on the parallax-image-plugin. All the other plugins are working fine :)

Example Video: https://www.useloom.com/share/0fa189082619495a98e391d024de1b09

Doing my best to figure out why, but I'm a little stumped?

**Comment by arekkas** [comment] 2017-11-14 14:51
Could you maybe provide an example codebase for reproduction?

**Comment by arekkas** [comment] 2017-11-14 15:00
Oh, you could maybe check the layers - it could be possible that the parallax background isn't clickable because the layer above it prohibits it

**Comment by KamesCG** [comment] 2017-11-14 15:17
I thought the same thing about the laying... I couldn't see anything immediately after debugging yesterday. Even attempted to realign children elements to see if they we're preventing anything.

I restarted the examples directory... For some reason I thought that didn't work in there either yesterday.

Let me do a little more debugging and get back to you.

**Comment by KamesCG** [comment] 2017-11-14 15:42
I know you're probably thinking "silly user" and you're probably right, but it looks like none of the cells are getting the "ory-cell-focused" css class when children are clicked, like in the example.

So maybe something I'm doing something to prevent that propagation back up to the parent cell?

**Comment by KamesCG** [comment] 2017-11-14 17:27
Thanks for even contemplating the problem :) I'm not sure what's causing the issue... Layering or Javascript.

I'm writing custom plugins, so I'll simply manually enable the "focus" for now. 

I'll update if I figure it out.

**Comment by macrozone** [comment] 2019-11-15 11:38
should be fixed now, please reopen if you still notice problems with it

**Closed by macrozone** 2019-11-15 11:38 UTC
