### ISSUE TITLE
Dragging a plugin block near a blank text block may delete the plugin

### ISSUE THREAD

**Issue by malz** [react-page/react-page#479] opened 2017-10-12 04:18 UTC
Hi there,

We've come across the following bug when we try and set the layout of an Ory Editor when we try and drag a plugin block against a blank Text block occasionally the black guideline will not appear and releasing the mouse will delete the dragged block. This does not occur when the Text Block has content in it.

Here's a gif of it happening:
![07052112798735eebab1384b91b621c0](https://user-images.githubusercontent.com/13263909/31479121-7727ce38-af58-11e7-8c82-353d5f99387c.gif)

**Comment by arekkas** [comment] 2017-10-12 14:07
Hm, that is very strange

**Comment by arekkas** [comment] 2017-10-15 09:27
Which browser is this? I tried reproducing it on FF and chrome at http://editor.ory.am with no luck.

**Comment by amalow** [comment] 2017-10-15 22:42
This happened on Chrome v61.0.3163.100 on OSX, I've been able to replicate it after messing around with it for a little it takes some time but once it happens in the session it can be replicated reliably.

**Comment by arekkas** [comment] 2017-10-16 06:26
Do you have redux devtools installed? If not, please install them and try to connect to the store. It would help to see what actions are triggered.

Also, is there some console output? Maybe this is a dupe of #472

**Comment by arekkas** [comment] 2017-10-16 06:31
If you're unable to connect redux dev tools, try to add a listener to the redux store manually. This can be achieved with `(new Editor()).store.subscribe()` see [here](http://redux.js.org/docs/api/Store.html#subscribe).

**Comment by amalow** [comment] 2017-10-16 21:57
No console output but I'll take a look with the Redux dev tools today.

**Comment by amalow** [comment] 2017-10-17 04:24
The CELL_INSERT_BELOW action fires however it appears that the plugin being dropped disappears from state.

**Comment by arekkas** [comment] 2017-10-17 06:23
Ok that's weird, can you show the payload of `CELL_INSERT_BELOW`? My guess is that we're trying to drop it over an ID that doesn't exist.

**Closed** 2020-05-21 12:48 UTC
Labels: bug
