### ISSUE TITLE
'Uncaught TypeError' when adding two plugins below eachother

### ISSUE THREAD

**Issue by JulesHuisman** [react-page/react-page#623] opened 2018-11-16 15:26 UTC
When I add two plugins below each other and I try to edit, I get the following error:

![capture](https://user-images.githubusercontent.com/26525996/48629944-3ad51780-e9bb-11e8-99c2-09923fd07912.PNG)

When I drag a image into a textbox the issue doesn't appear. 

This is my file structure:
```javascript
import React, { Component } from 'react';
import Ory from 'ory-editor-core';
import { Trash, DisplayModeToggle, Toolbar } from 'ory-editor-ui';
import { createEmptyState } from 'ory-editor-core';
import 'ory-editor-core/lib/index.css';
import 'ory-editor-ui/lib/index.css';
import './index.module.scss';

/**
*   Import plugins
*/

import { imagePlugin } from 'ory-editor-plugins-image';
import 'ory-editor-plugins-image/lib/index.css';
import slate from 'ory-editor-plugins-slate';
import 'ory-editor-plugins-slate/lib/index.css';
import native from 'ory-editor-plugins-default-native';

export const content = createEmptyState();

const fakeImageUploadService = (defaultUrl) => (file, reportProgress) => {
    return new Promise((resolve) => {
        let counter = 0;
        const interval = setInterval(() => {
            counter++;
            reportProgress(counter * 10);
            if (counter > 9) {
                clearInterval(interval);
                alert('This is a fake image upload service, please provide actual implementation via plugin properties');
                resolve({ url: defaultUrl });
            }
        }, 5000);
    });
};

const plugins = {
    content: [imagePlugin({ imageUpload: fakeImageUploadService('/images/react.png') }), slate()]
};

export const editor = new Ory({
    plugins,
    defaultPlugin: slate(),
    editables: [createEmptyState()],
    native
});

class Editor extends Component {

    render() {
        return (
            <div>
                <Trash editor={editor}/>
                <DisplayModeToggle editor={editor} />
                <Toolbar editor={editor} />
            </div>
        );
    }

}

export default Editor;
```

```javascript
import React, { Component } from 'react';
import { Editable } from 'ory-editor-core';
import { HTMLRenderer } from 'ory-editor-renderer';
import { content, editor, plugins } from 'components/Editor';
import './index.module.scss';

class Html extends Component {
    render() {
        return (
            <div>
                <Editable
                    editor={editor}
                    id={content.id}
                />
            </div>
        );
    }
}

export default Html;
```

**Comment by davidfurlong** [comment] 2019-05-23 07:01
closing due to no reproduction ability/old

**Closed by davidfurlong** 2019-05-23 07:01 UTC
