### ISSUE TITLE
upgrade to mui 5.x.x

### ISSUE THREAD

**Issue by bit314** [react-page/react-page#1106] opened 2021-11-18 05:04 UTC
Hi, the question is simple, are you planning to update the library to mui 5.x.x?

Now for correct work you need mui 4.x.x version. There are a lot of errors during the transition.

Replaced createMuiTheme and createTheme, etc.

**Comment by macrozone** [comment] 2021-12-30 13:28
duplicate of https://github.com/react-page/react-page/issues/1085

**Closed by macrozone** 2021-12-30 13:28 UTC
Labels: enhancement
