### ISSUE TITLE
Internet Explorer 11 does not support

### ISSUE THREAD

**Issue by kamrul-suhel** [react-page/react-page#871] opened 2020-10-26 09:07 UTC
Thank @macrozone that great, I thought my bundle size will be bigger that why I used HTMLRenderer. Thank for this & I tried with polyfill.io/v3/ to load into my _document.js file but still getting this error.

![ie-11 2](https://user-images.githubusercontent.com/6455590/97153621-b4124300-176a-11eb-9c04-6792d8395911.png)
![ie-11](https://user-images.githubusercontent.com/6455590/97153625-b4124300-176a-11eb-9f13-a7f0316e6407.png)

**Comment by macrozone** [comment] 2020-10-26 09:11
duplicate of https://github.com/react-page/react-page/issues/870

**Closed by macrozone** 2020-10-26 09:11 UTC
Labels: bug
