### ISSUE TITLE
SSR and MUI + JSS + <ThemeProvider>

### ISSUE THREAD

**Issue by nolandg** [react-page/react-page#600] opened 2018-09-26 00:06 UTC
Wondering if anyone has successfully integrated Ory into an SSR site? I'm attempting this now and it seems the way `<ThemeProvider>` works makes this impossible. By using it's own `<JssProvider>` and class name generator, I have no way of grabbing the stylesheets the JSS makes to inject on the server side. So first render is shit and then corrects as the JSS runs.

...which wouldn't be soooo bad but then on the client the re-instantiation of the class name generator resets the component count and all the class names after the first Ory component are screwed.

Am I missing something here? Is there a way to tell Ory to use my own `<JssProvider>` which is already wrapping all components?

**Comment by nolandg** [comment] 2018-09-26 20:09
As a test, I changed `<ThemeProvider>` to do nothing, just pass through it's `children` with a `<Fragment>` and it seems to work perfectly and use my own app's theme and doesn't break SSR. Is there interest in a PR for such functionality?

**Comment by davidfurlong** [comment] 2018-09-29 08:31
We do SSR, but I havent experienced the issue you're talking about.

**Comment by nolandg** [comment] 2018-09-30 20:12
@davidfurlong Thanks for the reply. Does your host app that uses Ory have it's own JSS provider and own MUI theme? Or is Ory the only part of the app that uses JSS?

**Comment by davidfurlong** [comment] 2018-10-01 07:01
> Ory the only part of the app that uses JSS

this

**Comment by aeneasr** [comment] 2018-10-01 08:01
Isn't this a dupe of #597?

**Comment by nolandg** [comment] 2018-10-01 16:37
@aeneasr Related but #597 doesn't address the more important issue of `<JssProvider>`. MUI theme passing is important but worst-case scenario is wrong theme. If Jss provider is not handled correctly, all styling after the first Ory component is lost and page looks like garbage. Having multiple overlapping MUI themes can actually be made to work and might be intentional. Having multiple JSS providers just breaks everything, mainly because of the duplicated class name generator which leads to server-client mismatches.

The way to solve this is for `<ThemeProvider>` to check if there's an upstream JSS provider and if so, not create a new one. Themes would be unaffected and whatever solution you implement for #597 would be unaffected since `<ThemeProvider>` can still provide a MUI theme without a JSS provider:

````jsx
class ThemeProvider extends Component {
  render() {
    return (
      // <JssProvider generateClassName={generateClassName}>
        <MuiThemeProvider theme={this.props.theme || theme}>
          {this.props.children}
        </MuiThemeProvider>
      // </JssProvider>
    );
  }
}
````
The above works great for me and preserves SSR in my entire app which makes use of its own MUI theme and JSS provider. Hot module reloading also works fine this way and doesn't dup the JSS provider on HMR.

**Comment by aeneasr** [comment] 2018-10-02 07:15
Ok I see, I'm sure `JssProvider` relies on context right? So there could be a way to check if the JssProvider is set up and disable it if it is. I think this should also be addressed along with #597 as it's really the same issue, just a different part of the system.

**Comment by macrozone** [comment] 2019-08-19 13:53
@nolandg  can you try the latest version? 

I would currently advice to use `HTMLRenderer` on pages that you SSR and have separate components (with Editable, Toolbar, etc.) for editors on other pages that you don't SSR. You can share the same plugins in both components.

E.g. in my app we use nextjs and  `react-admin` where we have a custom FieldType that uses react-page:

```
import { Paper } from "@material-ui/core";
import Editor, { createEmptyState, Editable } from "@react-page/core";
import "@react-page/core/lib/index.css";
import { DisplayModeToggle, Toolbar, Trash } from "@react-page/ui";
import "@react-page/ui/lib/index.css";
import { addField, FieldTitle } from "ra-core";
import React, { Fragment } from "react";
import plugins, { defaultPlugin } from "../../content/plugins";

// has to be a singleton...
const editor = new Editor({
  plugins,
  editables: [],
  defaultPlugin,
});

const ContentEditor = class extends React.Component<any, any> {
  public editorState: any = {
    id: null,
  };

  constructor(props) {
    super(props);
    // eslint-disable-next-line react/destructuring-assignment
    this.editorState = this.props.input.value || createEmptyState();

    editor.trigger.editable.update(this.editorState);
  }

  public render() {
    const {
      label,
      source,
      resource,
      isRequired,
      input: { onChange },
    } = this.props;

    return (
      <Fragment>
        <FieldTitle label={label} source={source} resource={resource} isRequired={isRequired} />
        <Paper elevation={5} style={{ padding: 20 }}>
          <Editable id={this.editorState.id} editor={editor} onChange={onChange} />
        </Paper>
        <Trash editor={editor} />
        <DisplayModeToggle editor={editor} />
        <Toolbar editor={editor} />
      </Fragment>
    );
  }
};

export default addField(ContentEditor);

```

and on  "frontend" side, we just use the HTMLRenderer:

```
  <HTMLRenderer plugins={plugins} state={content} />

```

as mentioned `plugins` points to the exact same array. In our case this looks like this:

```
import "@react-page/plugins-image/lib/index.css";

import divider from "@react-page/plugins-divider";
import { imagePlugin } from "@react-page/plugins-image";
import slate, { slatePlugins } from "@react-page/plugins-slate";
import "@react-page/plugins-slate/lib/index.css";

import styled from "styled-components";

import { selectFont } from "../../../utils/themeUtils";
import Heading from "../../layout/components/Heading";
import htmlPlugin from "./html/htmlPlugin";

// editor singleton

const Heading1 = styled(Heading).attrs({ level: 1 })``;
const Heading2 = styled(Heading).attrs({ level: 2 })``;
const Heading3 = styled(Heading).attrs({ level: 3 })``;

const Paragaph = styled.p`
  ${selectFont("textContent")};
  margin-bottom: 2em;
  em {
    font-style: italic;
  }
  strong {
    font-weight: bold;
  }
`;

const LI = styled.li`
  ${Paragaph} {
    margin-bottom: 0px;
  }
`;

const UL = styled.ul`
  margin-bottom: 2em;
  li {
    list-style-type: circle;
  }
`;

const OL = styled.ol`
  margin-bottom: 2em;
  li {
    list-style-type: decimal;
  }
`;
const HEADINGS = {
  "HEADINGS/HEADING-ONE": Heading1,
  "HEADINGS/HEADING-TWO": Heading2,
  "HEADINGS/HEADING-THREE": Heading3,
};

const LISTS = {
  "LISTS/UNORDERED-LIST": UL,
  "LISTS/ORDERED-LIST": OL,
  "LISTS/LIST-ITEM": LI,
};

const slatePlugin = slate([
  new slatePlugins.AlignmentPlugin(),
  new slatePlugins.EmphasizePlugin(),

  new slatePlugins.ListsPlugin({
    getComponent: ({ type }) => LISTS[type],
  }),
  new slatePlugins.ParagraphPlugin({
    getComponent: () => Paragaph,
  }),

  new slatePlugins.HeadingsPlugin({
    allowedLevels: [1, 2, 3],
    getComponent: ({ type }) => {
      return HEADINGS[type];
    },
  }),
  new slatePlugins.LinkPlugin(),
]);
export const defaultPlugin = slatePlugin;
export default {
  content: [htmlPlugin, divider, imagePlugin(), slatePlugin],
};

```

works so far with SSR

**Comment by PeterKottas** [comment] 2020-05-21 12:53
I think Marco's last comment should clear this up. Feel free to reopen if this is still an issue.

**Closed by PeterKottas** 2020-05-21 12:53 UTC
